# TODO: make mode into ternary
{{- $cluster := .Values.cluster.name }}
{{- range .Values.namespaces }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-app-config
  namespace: {{ . }}
data:
  DD_AGENT_HOST: datadog-agent.monitoring
  DD_LOGS_INJECTION: 'true'
  DD_RUNTIME_METRICS_ENABLED: 'true'
  DD_TAGS: "cluster:{{ $cluster }}{{- if eq . "studio-live" }},mode:live{{ else if eq . "studio-sandbox" }},mode:sandbox{{ else }}{{- end }}"
  DATADOG_TAGS: "cluster:{{ $cluster }}{{- if eq . "studio-live" }},mode:live{{ else if eq . "studio-sandbox" }},mode:sandbox{{ else }}{{- end }}"
  DD_TRACE_ANALYTICS_ENABLED: 'true'
{{- end }}
