apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-infra-root
  namespace: argocd
spec:
  project: infra-test
  source:
    repoURL: https://github.com/mvam75/argocd-testing.git
    path: infrastructure
    helm:
      valueFiles:
        - defaults.yaml
        - values-dev.yaml
  destination:
    namespace: argo-root
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
