apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  hub: gcr.io/istio-release
  tag: {{ .Values.versions.istioOperator }}-distroless
  components:
    cni:
      enabled: true
      k8s:
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
    pilot:
      enabled: true
      k8s:
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
  meshConfig:
    enableTracing: true
  values:
    cni:
      excludeNamespaces:
        - cert-manager
        - datadog
        - istio-system
        - kube-system
        - default
        - external-dns
        - istio-operator
        - kube-node-lease
        - kube-public
        - vswh
    global:
      proxy:
        tracer: datadog
      tracer:
        datadog:
          address: datadog.monitoring:8126
