apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  destination:
    namespace: vault-operator
    server: https://kubernetes.default.svc
  project: infra-testing
  source:
    chart: vault-operator
    repoURL: https://kubernetes-charts.banzaicloud.com
    targetRevision: 1.11.7
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
