apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: monitoring
spec:
  clusterName: dev-use2-1
  credentials:
    apiSecret:
      secretName: datadog-api-secret
      keyName: api-key
    appSecret:
      secretName: datadog-api-secret
      keyName: app-key
  agent:
    additionalAnnotations:
      iam.amazonaws.com/role: {{ .Values.dataDog.mskRole }}
    apm:
      enabled: true
      env:
        - name: DD_APM_IGNORE_RESOURCES
          value: 'GET /(auth||customers|core|settlement|eventstore-backup|kyc|webhooks|ledger.*)/health/.*$,GET /alive.*,GET /health*,GET health*,GET system/health*'
    config:
      collectEvents: true
      tags:
        - "environment:{{ .Values.cluster.environment }}"
        - "cluster:{{ .Values.cluster.name }}"
    env:
      - name: DD_CONTAINER_EXCLUDE_LOGS
        value: name:agent name:system
    process:
      enabled: true
      processCollectionEnabled: true
    log:
      enabled: true
      logsConfigContainerCollectAll: true
    rbac:
      create: true
    systemProbe:
      appArmorProfileName: unconfined
      bpfDebugEnabled: false
      enabled: false
      conntrackEnabled: true
    security:
      compliance:
        enabled: false
      runtime:
        enabled: false
    useExtendedDaemonset: true
  clusterAgent:
    config:
      admissionController:
        enabled: true
      clusterChecksEnabled: true
      collectEvents: true
      externalMetrics:
        enabled: true
      logLevel: info
    rbac:
      create: true  
  features:
    kubeStateMetricsCore:
      enabled: true
    orchestratorExplorer:
      enabled: true
    networkMonitoring:
      enabled: false
---

apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  namespace: monitoring
spec:
  ports:
    - name: ddstatsd
      protocol: UDP
      port: 8125
      targetPort: 8125
    - name: ddapm
      protocol: TCP
      port: 8126
      targetPort: 8126
  selector:
    agent.datadoghq.com/component: agent
    app.kubernetes.io/instance: agent
  type: ClusterIP
  sessionAffinity: None
