apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: {{ .Values.argo.clusterUrl }}
  project: {{ .Values.argo.project }}
  source:
    chart: external-dns
    helm:
      parameters:
        - name: policy
          value: upsert
        - name: sources[0]
          value: service
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.versions.externalDns }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
